# Copyright (c) 2026, AG2ai, Inc., AG2ai open-source projects maintainers and core contributors
#
# SPDX-License-Identifier: Apache-2.0

"""AG2 Beta V3 network layer.

Re-exports the public surface. Implementation is grouped by concern::

    autogen.beta.network
    ├── ids.py               UUID7 helper
    ├── errors.py            NetworkError hierarchy
    ├── identity.py          ActorIdentity / AuthBlock
    ├── rule.py              Rule (access / limits / transforms)
    ├── envelope.py          Envelope + stable event type names
    ├── session_types.py     SessionType enum + SessionMetadata
    ├── auth.py              AuthAdapter protocol + NoAuth
    ├── transport/           Link protocol + LocalLink
    ├── adapters/            SessionAdapter protocol + per-type implementations
    ├── hub/                 Hub, registry, rule storage, dispatch
    ├── client/              HubClient, ActorClient, Session handle
    └── policies/            SessionInboxPolicy
"""

from __future__ import annotations

from .adapters import (
    AdapterResult,
    AuctionAdapter,
    BroadcastAdapter,
    ConsultingAdapter,
    ConversationAdapter,
    DiscussionAdapter,
    NotificationAdapter,
    SessionAdapter,
)
from .auth import (
    ApiKeyAuth,
    AuthAdapter,
    AuthRegistry,
    JwtAuth,
    NoAuth,
    default_registry,
    dev_registry,
)
from .client import (
    ActorClient,
    ActorClientInject,
    HubClient,
    HubInject,
    HumanCliSurface,
    HumanClient,
    HumanScriptedSurface,
    HumanSurface,
    NotifyHandler,
    Session,
    SessionInject,
    Task,
    TaskInject,
    human_cli_client,
)
from .client.transforms import (
    HttpTransform,
    NamedTransform,
    PythonTransform,
    Transform,
    TransformContext,
    TransformError,
    TransformLookupError,
    TransformPipeline,
    TransformRegistry,
    TransformRejected,
)
from .envelope import (
    EV_ERROR,
    EV_SESSION_CLOSED,
    EV_SESSION_INVITE,
    EV_SESSION_INVITE_ACK,
    EV_SESSION_INVITE_REJECT,
    EV_SESSION_OPENED,
    EV_TASK_ASSIGNED,
    EV_TASK_CANCELLED,
    EV_TASK_ERROR,
    EV_TASK_EXPIRED,
    EV_TASK_PHASE_COMPLETED,
    EV_TASK_PHASE_ENTERED,
    EV_TASK_PROGRESS,
    EV_TASK_RESULT,
    EV_TEXT,
    TASK_EVENT_TYPES,
    TASK_TERMINAL_EVENT_TYPES,
    Envelope,
)
from .errors import (
    AccessDeniedError,
    AuthError,
    DuplicateRegistrationError,
    FrameError,
    InboxError,
    InboxFullError,
    InviteRejectedError,
    LimitExceededError,
    LinkClosedError,
    NetworkError,
    RegistryError,
    RuleViolationError,
    SessionClosedError,
    SessionError,
    SessionTypeError,
    TaskCancelledError,
    TaskError,
    TaskExpiredError,
    TaskFailedError,
    TaskStateError,
    TimeoutError,
    TransportError,
    UnknownActorError,
    UnknownSessionError,
    UnknownTaskError,
)
from .events import (
    BUILTIN_EVENT_TYPES,
    EventRegistry,
    EventTypeSpec,
    UnknownEventTypeError,
)
from .http import HttpServer, build_app
from .hub import Hub, HubConfig
from .identity import ActorIdentity, AuthBlock
from .ids import extract_ms, new_id, uuid7
from .policies import (
    ACTOR_CLIENT_DEP,
    HUB_DEP,
    SESSION_DEP,
    SESSION_ID_VAR,
    TASK_DEP,
    PreviousOnlyInboxPolicy,
    SessionInboxPolicy,
)
from .rule import (
    AccessBlock,
    InboxBlock,
    KnowledgeAccess,
    LimitsBlock,
    RateBlock,
    Rule,
    SessionTypeAccess,
    SubscribeAccess,
    TransformSpec,
    TransformStage,
)
from .session_types import (
    Participant,
    ParticipantRole,
    SessionMetadata,
    SessionState,
    SessionType,
)
from .task import (
    TERMINAL_TASK_STATES,
    TaskMetadata,
    TaskPhase,
    TaskSpec,
    TaskState,
)
from .transport import (
    Link,
    LinkClient,
    LinkEndpoint,
    LocalLink,
    WsLinkClient,
    WsLinkServer,
)

__all__ = (
    "BUILTIN_EVENT_TYPES",
    "EV_ERROR",
    "EV_SESSION_CLOSED",
    "EV_SESSION_INVITE",
    "EV_SESSION_INVITE_ACK",
    "EV_SESSION_INVITE_REJECT",
    "EV_SESSION_OPENED",
    "EV_TASK_ASSIGNED",
    "EV_TASK_CANCELLED",
    "EV_TASK_ERROR",
    "EV_TASK_EXPIRED",
    "EV_TASK_PHASE_COMPLETED",
    "EV_TASK_PHASE_ENTERED",
    "EV_TASK_PROGRESS",
    "EV_TASK_RESULT",
    "EV_TEXT",
    "ACTOR_CLIENT_DEP",
    "HUB_DEP",
    "SESSION_DEP",
    "SESSION_ID_VAR",
    "TASK_DEP",
    "TASK_EVENT_TYPES",
    "TASK_TERMINAL_EVENT_TYPES",
    "TERMINAL_TASK_STATES",
    "AccessBlock",
    "AccessDeniedError",
    "ActorClient",
    "ActorClientInject",
    "ActorIdentity",
    "AdapterResult",
    "ApiKeyAuth",
    "AuctionAdapter",
    "AuthAdapter",
    "AuthBlock",
    "AuthError",
    "AuthRegistry",
    "BroadcastAdapter",
    "ConsultingAdapter",
    "ConversationAdapter",
    "DiscussionAdapter",
    "DuplicateRegistrationError",
    "Envelope",
    "EventRegistry",
    "EventTypeSpec",
    "FrameError",
    "HttpServer",
    "HttpTransform",
    "Hub",
    "HubClient",
    "HubConfig",
    "HubInject",
    "HumanCliSurface",
    "HumanClient",
    "HumanScriptedSurface",
    "HumanSurface",
    "InboxBlock",
    "InboxError",
    "InboxFullError",
    "InviteRejectedError",
    "JwtAuth",
    "KnowledgeAccess",
    "LimitExceededError",
    "LimitsBlock",
    "Link",
    "LinkClient",
    "LinkClosedError",
    "LinkEndpoint",
    "LocalLink",
    "NamedTransform",
    "NetworkError",
    "NoAuth",
    "NotificationAdapter",
    "NotifyHandler",
    "Participant",
    "ParticipantRole",
    "PreviousOnlyInboxPolicy",
    "PythonTransform",
    "RateBlock",
    "RegistryError",
    "Rule",
    "RuleViolationError",
    "Session",
    "SessionAdapter",
    "SessionClosedError",
    "SessionError",
    "SessionInboxPolicy",
    "SessionInject",
    "SessionMetadata",
    "SessionState",
    "SessionType",
    "SessionTypeAccess",
    "SessionTypeError",
    "SubscribeAccess",
    "Task",
    "TaskCancelledError",
    "TaskError",
    "TaskExpiredError",
    "TaskFailedError",
    "TaskInject",
    "TaskMetadata",
    "TaskPhase",
    "TaskSpec",
    "TaskState",
    "TaskStateError",
    "TimeoutError",
    "Transform",
    "TransformContext",
    "TransformError",
    "TransformLookupError",
    "TransformPipeline",
    "TransformRegistry",
    "TransformRejected",
    "TransformSpec",
    "TransformStage",
    "TransportError",
    "UnknownActorError",
    "UnknownEventTypeError",
    "UnknownSessionError",
    "UnknownTaskError",
    "WsLinkClient",
    "WsLinkServer",
    "build_app",
    "default_registry",
    "dev_registry",
    "extract_ms",
    "human_cli_client",
    "new_id",
    "uuid7",
)
