#!/usr/bin/env python3
"""Algorithmic Trading Desk — full customization demo.

Demonstrates every extensibility point of the AG2 network framework:
custom priority scheme, custom events, routing plugins, system plugins,
context harnesses, and conflict resolution.

4 agents: Analyst, Trader, Risk Manager, Compliance Officer.
Topology: Pipeline(RiskGate, RateLimiter) with ComplianceAudit + Telemetry.

Usage:
    python playground/06_trading_desk/main.py
    python playground/06_trading_desk/main.py --scenario 2
    python playground/06_trading_desk/main.py --scenario 3
    python playground/06_trading_desk/main.py --model gemini-3-flash-preview
"""

from __future__ import annotations

import asyncio
import random
import sys
import time
from datetime import datetime
from enum import IntEnum
from typing import TYPE_CHECKING, Any

from autogen.beta import Actor, ObserverAlert, tool
from autogen.beta.config.gemini import GeminiConfig
from autogen.beta.events import BaseEvent
from autogen.beta.events.conditions import TypeCondition
from autogen.beta.network import (
    DelegationRejected,
    DelegationRequest,
    DelegationResult,
    Envelope,
    HighestPriorityWins,
    HubContext,
    Network,
    Pipeline,
    RateLimiter,
    TelemetryPlugin,
    register_event,
    BasePlugin,
)

if TYPE_CHECKING:
    from autogen.beta.network.hub import Hub

# =====================================================================
# ANSI helpers
# =====================================================================

_BOLD = "\033[1m"
_DIM = "\033[2m"
_RESET = "\033[0m"
_CYAN = "\033[96m"
_GREEN = "\033[92m"
_YELLOW = "\033[93m"
_RED = "\033[91m"
_MAGENTA = "\033[95m"
_WHITE = "\033[97m"
_BLUE = "\033[94m"

# =====================================================================
# Custom Priority
# =====================================================================


class TradePriority(IntEnum):
    """Trade priority levels. Market orders beat limit orders; risk alerts trump all."""

    ANALYSIS = 0
    LIMIT_ORDER = 1
    MARKET_ORDER = 2
    RISK_ALERT = 3


class TradePriorityScheme:
    """Custom priority scheme for the trading desk."""

    def compare(self, a: Any, b: Any) -> int:
        return int(a) - int(b)


# =====================================================================
# Custom Events
# =====================================================================


@register_event
class PriceSignal(BaseEvent):
    """A market price signal generated by the analyst."""

    symbol: str
    price: float
    change_pct: float
    signal_type: str  # "buy" | "sell" | "hold"


@register_event
class TradeExecution(BaseEvent):
    """A trade execution event from the trader."""

    order_id: str
    symbol: str
    side: str
    quantity: int
    price: float


# =====================================================================
# Custom Plugins
# =====================================================================


class RiskGate(BasePlugin):
    """Routing plugin -- sits in the topology pipeline.

    Checks delegations that involve trading. If portfolio exposure exceeds
    the maximum, the delegation is vetoed (returns None).
    """

    def __init__(self, max_exposure: float = 1_000_000) -> None:
        self._max_exposure = max_exposure
        self._hub: Hub | None = None
        self.total_checked = 0
        self.total_vetoed = 0

    def install(self, hub: Hub) -> None:
        self._hub = hub

    def uninstall(self) -> None:
        self._hub = None

    async def process(self, envelope: Envelope, ctx: HubContext) -> Envelope | None:
        self.total_checked += 1
        event = envelope.event

        # Only gate trade-related delegations
        task_text = ""
        if isinstance(event, DelegationRequest):
            task_text = event.task.lower()

        trade_keywords = ("execute", "trade", "order", "buy", "sell", "place")
        is_trade = any(kw in task_text for kw in trade_keywords)

        if is_trade and self._hub is not None:
            exposure = await ctx.hub.state_store.get("portfolio_exposure")
            if exposure is not None and exposure > self._max_exposure:
                self.total_vetoed += 1
                return None  # Veto the delegation

        return envelope


class ComplianceAudit(BasePlugin):
    """System plugin -- observes hub.stream, does NOT sit in delegation path.

    Subscribes to DelegationRequest and DelegationResult events and
    records them in an in-memory audit trail.
    """

    def __init__(self) -> None:
        self._hub: Hub | None = None
        self._sub_ids: list = []
        self._audit_log: list[dict[str, Any]] = []

    def install(self, hub: Hub) -> None:
        self._hub = hub
        self._sub_ids.append(
            hub.stream.subscribe(
                self._on_request,
                condition=TypeCondition(DelegationRequest),
            )
        )
        self._sub_ids.append(
            hub.stream.subscribe(
                self._on_result,
                condition=TypeCondition(DelegationResult),
            )
        )
        self._sub_ids.append(
            hub.stream.subscribe(
                self._on_rejected,
                condition=TypeCondition(DelegationRejected),
            )
        )

    def uninstall(self) -> None:
        if self._hub:
            for sub_id in self._sub_ids:
                self._hub.stream.unsubscribe(sub_id)
        self._sub_ids.clear()
        self._hub = None

    async def _on_request(self, event: DelegationRequest) -> None:
        self._audit_log.append({
            "time": datetime.now().strftime("%H:%M:%S.%f")[:-3],
            "type": "DELEGATION_REQUEST",
            "source": event.source,
            "target": event.target,
            "task_preview": event.task[:100],
        })

    async def _on_result(self, event: DelegationResult) -> None:
        self._audit_log.append({
            "time": datetime.now().strftime("%H:%M:%S.%f")[:-3],
            "type": "DELEGATION_RESULT",
            "source": event.source,
            "target": event.target,
            "result_preview": event.result[:100],
        })

    async def _on_rejected(self, event: DelegationRejected) -> None:
        self._audit_log.append({
            "time": datetime.now().strftime("%H:%M:%S.%f")[:-3],
            "type": "DELEGATION_REJECTED",
            "source": event.source,
            "target": event.target,
            "reason": event.reason,
        })

    def get_audit_log(self) -> list[dict[str, Any]]:
        """Return the full audit trail."""
        return list(self._audit_log)


# =====================================================================
# Tools — Analyst
# =====================================================================


@tool
async def fetch_market_data(symbol: str) -> str:
    """Fetch current market data for a symbol.

    Args:
        symbol: Stock ticker symbol (e.g. NVDA, AAPL, TSLA).
    """
    base_prices = {"NVDA": 892.50, "AAPL": 178.25, "TSLA": 245.80, "GOOGL": 155.40, "MSFT": 415.60}
    base = base_prices.get(symbol, random.uniform(50, 500))
    price = round(base * (1 + random.uniform(-0.05, 0.05)), 2)
    volume = random.randint(5_000_000, 80_000_000)
    high_52 = round(price * random.uniform(1.1, 1.5), 2)
    low_52 = round(price * random.uniform(0.5, 0.9), 2)
    return (
        f"Market Data for {symbol}:\n"
        f"  Price: ${price:,.2f}\n"
        f"  Volume: {volume:,}\n"
        f"  52-Week High: ${high_52:,.2f}\n"
        f"  52-Week Low: ${low_52:,.2f}\n"
        f"  Market Cap: ${price * random.randint(1_000, 15_000)}M"
    )


@tool
async def run_technical_analysis(symbol: str) -> str:
    """Run technical analysis on a symbol.

    Args:
        symbol: Stock ticker symbol.
    """
    rsi = round(random.uniform(20, 80), 1)
    macd = round(random.uniform(-5, 5), 2)
    sma_20 = round(random.uniform(150, 900), 2)
    sma_50 = round(random.uniform(140, 880), 2)
    if rsi > 65 and macd > 0:
        signal = "STRONG BUY"
    elif rsi > 50 and macd > 0:
        signal = "BUY"
    elif rsi < 35 and macd < 0:
        signal = "STRONG SELL"
    elif rsi < 50 and macd < 0:
        signal = "SELL"
    else:
        signal = "HOLD"
    return (
        f"Technical Analysis for {symbol}:\n"
        f"  RSI(14): {rsi}\n"
        f"  MACD: {macd}\n"
        f"  SMA(20): ${sma_20:,.2f}\n"
        f"  SMA(50): ${sma_50:,.2f}\n"
        f"  Signal: {signal}"
    )


@tool
async def generate_trade_signal(symbol: str, direction: str, confidence: float) -> str:
    """Generate a trade signal recommendation.

    Args:
        symbol: Stock ticker symbol.
        direction: Trade direction ("buy" or "sell").
        confidence: Confidence level 0.0 to 1.0.
    """
    signal_id = f"SIG-{random.randint(1000, 9999)}"
    return (
        f"Trade Signal Generated:\n"
        f"  Signal ID: {signal_id}\n"
        f"  Symbol: {symbol}\n"
        f"  Direction: {direction.upper()}\n"
        f"  Confidence: {confidence:.0%}\n"
        f"  Timestamp: {datetime.now().strftime('%H:%M:%S')}\n"
        f"  Status: PENDING EXECUTION"
    )


analyst_tools = [fetch_market_data, run_technical_analysis, generate_trade_signal]


# =====================================================================
# Tools — Trader
# =====================================================================


@tool
async def place_order(symbol: str, side: str, quantity: int, order_type: str = "market") -> str:
    """Place a trade order.

    Args:
        symbol: Stock ticker symbol.
        side: "buy" or "sell".
        quantity: Number of shares.
        order_type: "market" or "limit".
    """
    order_id = f"ORD-{random.randint(10000, 99999)}"
    base_prices = {"NVDA": 892.50, "AAPL": 178.25, "TSLA": 245.80, "GOOGL": 155.40, "MSFT": 415.60}
    base = base_prices.get(symbol, random.uniform(50, 500))
    slippage = random.uniform(-0.5, 0.5) if order_type == "market" else 0
    fill_price = round(base + slippage, 2)
    total = round(fill_price * quantity, 2)
    return (
        f"Order Executed:\n"
        f"  Order ID: {order_id}\n"
        f"  Symbol: {symbol}\n"
        f"  Side: {side.upper()}\n"
        f"  Quantity: {quantity:,}\n"
        f"  Type: {order_type.upper()}\n"
        f"  Fill Price: ${fill_price:,.2f}\n"
        f"  Total Value: ${total:,.2f}\n"
        f"  Status: FILLED"
    )


@tool
async def check_position(symbol: str) -> str:
    """Check current position for a symbol.

    Args:
        symbol: Stock ticker symbol.
    """
    qty = random.randint(0, 5000)
    avg_cost = round(random.uniform(100, 800), 2)
    current = round(avg_cost * (1 + random.uniform(-0.15, 0.15)), 2)
    pnl = round((current - avg_cost) * qty, 2)
    return (
        f"Position for {symbol}:\n"
        f"  Shares: {qty:,}\n"
        f"  Avg Cost: ${avg_cost:,.2f}\n"
        f"  Current Price: ${current:,.2f}\n"
        f"  Unrealized P&L: ${pnl:+,.2f}"
    )


@tool
async def calculate_pnl(symbol: str) -> str:
    """Calculate detailed P&L for a symbol.

    Args:
        symbol: Stock ticker symbol.
    """
    realized = round(random.uniform(-50000, 100000), 2)
    unrealized = round(random.uniform(-30000, 80000), 2)
    fees = round(random.uniform(50, 500), 2)
    net = round(realized + unrealized - fees, 2)
    return (
        f"P&L Report for {symbol}:\n"
        f"  Realized P&L: ${realized:+,.2f}\n"
        f"  Unrealized P&L: ${unrealized:+,.2f}\n"
        f"  Fees/Commission: ${fees:,.2f}\n"
        f"  Net P&L: ${net:+,.2f}"
    )


trader_tools = [place_order, check_position, calculate_pnl]


# =====================================================================
# Tools — Risk Manager
# =====================================================================


@tool
async def calculate_var(portfolio: str, confidence_level: float = 0.95) -> str:
    """Calculate Value at Risk for a portfolio.

    Args:
        portfolio: Portfolio name or description.
        confidence_level: Confidence level (e.g. 0.95 or 0.99).
    """
    var_1d = round(random.uniform(50000, 500000), 2)
    var_10d = round(var_1d * 3.16, 2)  # sqrt(10) scaling
    return (
        f"VaR Calculation ({portfolio}):\n"
        f"  Confidence: {confidence_level:.0%}\n"
        f"  1-Day VaR: ${var_1d:,.2f}\n"
        f"  10-Day VaR: ${var_10d:,.2f}\n"
        f"  Method: Historical simulation\n"
        f"  Observation period: 252 trading days"
    )


@tool
async def check_exposure(sector: str) -> str:
    """Check portfolio exposure to a sector.

    Args:
        sector: Sector name (e.g. "technology", "energy", "healthcare").
    """
    exposure_pct = round(random.uniform(5, 45), 1)
    limit_pct = 40.0
    notional = round(random.uniform(500000, 5000000), 2)
    status = "WITHIN LIMITS" if exposure_pct < limit_pct else "LIMIT BREACH"
    return (
        f"Sector Exposure ({sector.upper()}):\n"
        f"  Exposure: {exposure_pct}% (limit: {limit_pct}%)\n"
        f"  Notional: ${notional:,.2f}\n"
        f"  Status: {status}\n"
        f"  Utilization: {exposure_pct / limit_pct:.0%} of limit"
    )


@tool
async def set_risk_limit(metric: str, value: float) -> str:
    """Set a risk limit for a metric.

    Args:
        metric: Risk metric name (e.g. "max_var", "max_exposure", "max_drawdown").
        value: Limit value.
    """
    return (
        f"Risk Limit Updated:\n"
        f"  Metric: {metric}\n"
        f"  New Limit: {value:,.2f}\n"
        f"  Effective: {datetime.now().strftime('%H:%M:%S')}\n"
        f"  Status: ACTIVE"
    )


risk_tools = [calculate_var, check_exposure, set_risk_limit]


# =====================================================================
# Tools — Compliance Officer
# =====================================================================


@tool
async def check_trade_rules(trade_details: str) -> str:
    """Check a trade against regulatory rules.

    Args:
        trade_details: Description of the trade to check.
    """
    rules = [
        ("Reg T margin requirements", "PASS"),
        ("Pattern day trader check", random.choice(["PASS", "PASS", "FLAG"])),
        ("Insider trading screen", "PASS"),
        ("Short sale restrictions", random.choice(["PASS", "PASS", "REVIEW"])),
        ("Position concentration limits", "PASS"),
    ]
    lines = ["Regulatory Compliance Check:"]
    for rule, status in rules:
        marker = "OK" if status == "PASS" else status
        lines.append(f"  [{marker}] {rule}")
    flags = sum(1 for _, s in rules if s != "PASS")
    lines.append(f"  Overall: {'APPROVED' if flags == 0 else f'{flags} FLAG(S) - REVIEW REQUIRED'}")
    return "\n".join(lines)


@tool
async def generate_audit_report(period: str) -> str:
    """Generate a compliance audit report.

    Args:
        period: Reporting period (e.g. "today", "this_week", "2024-Q1").
    """
    total_trades = random.randint(50, 200)
    flagged = random.randint(0, 5)
    violations = random.randint(0, 2)
    report_id = f"AUD-{datetime.now().strftime('%Y%m%d')}-{random.randint(100, 999)}"
    return (
        f"Compliance Audit Report ({period}):\n"
        f"  Report ID: {report_id}\n"
        f"  Total Trades Reviewed: {total_trades}\n"
        f"  Flagged for Review: {flagged}\n"
        f"  Violations Found: {violations}\n"
        f"  Regulatory Filings: Up to date\n"
        f"  Best Execution: {'Compliant' if random.random() > 0.1 else 'REVIEW NEEDED'}\n"
        f"  Status: {'CLEAN' if violations == 0 else 'ACTION REQUIRED'}"
    )


@tool
async def flag_violation(description: str, severity: str = "medium") -> str:
    """Flag a compliance violation.

    Args:
        description: Description of the violation.
        severity: Severity level ("low", "medium", "high", "critical").
    """
    vid = f"VIO-{random.randint(1000, 9999)}"
    return (
        f"Compliance Violation Flagged:\n"
        f"  Violation ID: {vid}\n"
        f"  Severity: {severity.upper()}\n"
        f"  Description: {description}\n"
        f"  Time: {datetime.now().strftime('%H:%M:%S')}\n"
        f"  Status: OPEN - INVESTIGATION REQUIRED"
    )


compliance_tools = [check_trade_rules, generate_audit_report, flag_violation]


# =====================================================================
# Scenarios
# =====================================================================

SCENARIOS = {
    1: (
        "Market Analysis",
        "analyst",
        "Analyze NVDA, AAPL, and TSLA. Generate trade signals for any "
        "opportunities. Delegate to trader for execution on strong signals.",
    ),
    2: (
        "Risk Alert",
        "risk-manager",
        "ALERT: Portfolio exposure to tech sector has reached 85% of limit. "
        "Current VaR exceeds threshold. Assess situation, check with "
        "compliance, and take corrective action.",
    ),
    3: (
        "End of Day",
        "compliance-officer",
        "Generate end-of-day compliance report. Review all trades executed "
        "today. Check with risk-manager for current exposure levels. "
        "Flag any violations.",
    ),
}


# =====================================================================
# Main
# =====================================================================


async def main() -> None:
    # -- Parse CLI args -----------------------------------------------
    model = "gemini-3.1-pro-preview"
    if "--model" in sys.argv:
        model = sys.argv[sys.argv.index("--model") + 1]

    if "--scenario" in sys.argv:
        num = int(sys.argv[sys.argv.index("--scenario") + 1])
        title, entry_agent, task_message = SCENARIOS[num]
    else:
        title, entry_agent, task_message = SCENARIOS[1]

    # -- Create actors ------------------------------------------------
    analyst = Actor(
        "analyst",
        prompt=(
            "You are a Market Analyst on an algorithmic trading desk.\n"
            "Your job:\n"
            "1. Analyze markets using fetch_market_data and run_technical_analysis\n"
            "2. Generate trade signals using generate_trade_signal for strong opportunities\n"
            "3. When you find a strong signal (BUY or SELL), use discover_agents to find\n"
            "   agents with 'execution' capability, then delegate_to the trader with\n"
            "   clear instructions on what to execute\n"
            "4. Summarize your analysis and any delegated trades\n\n"
            "Be decisive — if the signal is strong, delegate for execution."
        ),
        config=GeminiConfig(model=model, temperature=0.3),
        tools=analyst_tools,
    )

    trader = Actor(
        "trader",
        prompt=(
            "You are a Trader on an algorithmic trading desk.\n"
            "Your job:\n"
            "1. Receive trade signals and check current positions with check_position\n"
            "2. Place orders using place_order when instructed\n"
            "3. Calculate P&L with calculate_pnl as needed\n"
            "4. If a trade is large or risky, use discover_agents to find agents with\n"
            "   'risk' capability and delegate to the risk-manager for approval\n"
            "5. Report execution results clearly\n\n"
            "Always check position before trading. Report fills accurately."
        ),
        config=GeminiConfig(model=model, temperature=0.3),
        tools=trader_tools,
    )

    risk_manager = Actor(
        "risk-manager",
        prompt=(
            "You are the Risk Manager on an algorithmic trading desk.\n"
            "Your job:\n"
            "1. Monitor portfolio risk using calculate_var\n"
            "2. Check sector exposure using check_exposure\n"
            "3. Set risk limits using set_risk_limit when needed\n"
            "4. If you find compliance concerns, use discover_agents to find agents\n"
            "   with 'regulatory' or 'audit' capability and delegate to the\n"
            "   compliance-officer\n"
            "5. Provide clear risk assessments and recommendations\n\n"
            "Be conservative — protect the firm from excessive risk."
        ),
        config=GeminiConfig(model=model, temperature=0.3),
        tools=risk_tools,
    )

    compliance_officer = Actor(
        "compliance-officer",
        prompt=(
            "You are the Compliance Officer on an algorithmic trading desk.\n"
            "Your job:\n"
            "1. Check trades against regulatory rules using check_trade_rules\n"
            "2. Generate audit reports using generate_audit_report\n"
            "3. Flag violations using flag_violation\n"
            "4. When you need risk data, use discover_agents to find agents with\n"
            "   'risk' or 'exposure' capability and delegate to the risk-manager\n"
            "5. Ensure all activities are properly documented\n\n"
            "Be thorough — regulatory compliance is non-negotiable."
        ),
        config=GeminiConfig(model=model, temperature=0.3),
        tools=compliance_tools,
    )

    # -- Create network with full customization -----------------------
    risk_gate = RiskGate(max_exposure=1_000_000)
    compliance_audit = ComplianceAudit()
    telemetry = TelemetryPlugin()

    network = Network(
        topology=Pipeline(risk_gate, RateLimiter(max_per_minute=30)),
        plugins=[compliance_audit, telemetry],
        priority_scheme=TradePriorityScheme(),
        conflict_resolver=HighestPriorityWins(),
        max_delegation_depth=5,
    )

    # -- Register actors ----------------------------------------------
    await network.register(
        analyst,
        capabilities=["analysis", "research", "signals"],
        description="Market analyst - researches securities and generates trade signals",
    )
    await network.register(
        trader,
        capabilities=["execution", "orders", "positions"],
        description="Trader - executes orders and manages positions",
    )
    await network.register(
        risk_manager,
        capabilities=["risk", "exposure", "limits"],
        description="Risk manager - monitors portfolio risk and sets limits",
    )
    await network.register(
        compliance_officer,
        capabilities=["regulatory", "audit", "reporting"],
        description="Compliance officer - ensures regulatory compliance",
    )

    # -- Subscribe to hub stream for live logging ---------------------
    async def _on_hub_event(event: object) -> None:
        ts = datetime.now().strftime("%H:%M:%S.%f")[:-3]
        if isinstance(event, DelegationRequest):
            print(
                f"  {_DIM}{ts}{_RESET}  "
                f"{_MAGENTA}{_BOLD}ROUTE{_RESET}  "
                f"{_MAGENTA}{event.source.upper()} -> {event.target.upper()}{_RESET}"
            )
            preview = event.task[:120].replace("\n", " ")
            print(f"  {_DIM}{' ' * 12}{_RESET}         {_DIM}{preview}{'...' if len(event.task) > 120 else ''}{_RESET}")
        elif isinstance(event, DelegationResult):
            print(
                f"  {_DIM}{ts}{_RESET}  "
                f"{_GREEN}{_BOLD}DONE {_RESET}  "
                f"{_GREEN}{event.target.upper()} completed -> {event.source.upper()}{_RESET}"
            )
        elif isinstance(event, DelegationRejected):
            print(
                f"  {_DIM}{ts}{_RESET}  "
                f"{_RED}{_BOLD}VETO {_RESET}  "
                f"{_RED}{event.source.upper()} -> {event.target.upper()}: {event.reason}{_RESET}"
            )
        elif isinstance(event, ObserverAlert):
            print(
                f"  {_DIM}{ts}{_RESET}  "
                f"{_YELLOW}{_BOLD}ALERT{_RESET}  "
                f"{_YELLOW}[{event.severity.value}] {event.message}{_RESET}"
            )

    network.hub.stream.subscribe(_on_hub_event)

    # -- Print header -------------------------------------------------
    print()
    print(f"  {_BOLD}{'=' * 64}{_RESET}")
    print(f"  {_BOLD}ALGORITHMIC TRADING DESK{_RESET}  {_DIM}(06_trading_desk){_RESET}")
    print(f"  {_BOLD}{'=' * 64}{_RESET}")
    print()
    print(f"  {_CYAN}Scenario:{_RESET}   {title}")
    print(f"  {_CYAN}Model:{_RESET}      {model}")
    print(f"  {_CYAN}Entry:{_RESET}      {entry_agent}")
    print(f"  {_CYAN}Actors:{_RESET}     analyst, trader, risk-manager, compliance-officer")
    print()
    print(f"  {_BLUE}Customization points:{_RESET}")
    print("    Priority:   TradePriorityScheme (ANALYSIS < LIMIT < MARKET < RISK_ALERT)")
    print("    Events:     PriceSignal, TradeExecution (custom @register_event)")
    print("    Topology:   Pipeline(RiskGate, RateLimiter)")
    print("    Plugins:    ComplianceAudit (system), TelemetryPlugin (system)")
    print("    Conflict:   HighestPriorityWins")
    print()
    print(f"  {_BOLD}Task:{_RESET}")
    words = task_message.split()
    line = "    "
    for w in words:
        if len(line) + len(w) + 1 > 76:
            print(line)
            line = "    " + w
        else:
            line += " " + w if len(line) > 4 else w
    if len(line) > 4:
        print(line)
    print()
    print(f"  {_DIM}{'─' * 64}{_RESET}")
    print(
        f"  {_BOLD}Log legend:{_RESET}  "
        f"{_MAGENTA}ROUTE{_RESET}=delegation  "
        f"{_GREEN}DONE{_RESET}=completed  "
        f"{_RED}VETO{_RESET}=rejected  "
        f"{_YELLOW}ALERT{_RESET}=signal"
    )
    print(f"  {_DIM}{'─' * 64}{_RESET}")
    print()

    # -- Run ----------------------------------------------------------
    t0 = time.monotonic()
    reply = await network.ask(entry_agent, task_message)
    elapsed = time.monotonic() - t0

    # -- Print result -------------------------------------------------
    print()
    print(f"  {_BOLD}{'=' * 64}{_RESET}")
    print(f"  {_GREEN}{_BOLD}TRADING DESK RESPONSE{_RESET}  {_DIM}({elapsed:.1f}s){_RESET}")
    print(f"  {_BOLD}{'=' * 64}{_RESET}")
    print()
    for rline in (reply.body or "").split("\n"):
        print(f"  {rline}")
    print()

    # -- Print plugin metrics -----------------------------------------
    print(f"  {_BOLD}{'─' * 64}{_RESET}")
    print(f"  {_BLUE}{_BOLD}PLUGIN METRICS{_RESET}")
    print(f"  {_BOLD}{'─' * 64}{_RESET}")
    print()

    # Risk Gate
    print(f"  {_CYAN}RiskGate (topology/routing):{_RESET}")
    print(f"    Delegations checked: {risk_gate.total_checked}")
    print(f"    Delegations vetoed:  {risk_gate.total_vetoed}")
    print()

    # Telemetry
    print(f"  {_CYAN}TelemetryPlugin (system/observer):{_RESET}")
    print(f"    Total delegations:   {telemetry.metrics.total_delegations}")
    print(f"    Total completions:   {telemetry.metrics.total_completions}")
    if telemetry.metrics.by_source:
        print(f"    By source:           {dict(telemetry.metrics.by_source)}")
    if telemetry.metrics.by_target:
        print(f"    By target:           {dict(telemetry.metrics.by_target)}")
    print()

    # Compliance Audit
    audit_log = compliance_audit.get_audit_log()
    print(f"  {_CYAN}ComplianceAudit (system/observer):{_RESET}")
    print(f"    Audit entries:       {len(audit_log)}")
    print()
    if audit_log:
        print(f"  {_BOLD}{'─' * 64}{_RESET}")
        print(f"  {_BLUE}{_BOLD}COMPLIANCE AUDIT LOG{_RESET}")
        print(f"  {_BOLD}{'─' * 64}{_RESET}")
        print()
        for entry in audit_log:
            etype = entry["type"]
            if etype == "DELEGATION_REQUEST":
                color = _MAGENTA
                detail = f"{entry['source']} -> {entry['target']}: {entry['task_preview']}"
            elif etype == "DELEGATION_RESULT":
                color = _GREEN
                detail = f"{entry['source']} -> {entry['target']}: {entry['result_preview']}"
            elif etype == "DELEGATION_REJECTED":
                color = _RED
                detail = f"{entry['source']} -> {entry['target']}: {entry['reason']}"
            else:
                color = _WHITE
                detail = str(entry)
            print(f"    {_DIM}{entry['time']}{_RESET}  {color}{etype}{_RESET}")
            # Word-wrap the detail
            if len(detail) > 70:
                detail = detail[:70] + "..."
            print(f"    {' ' * 12}  {_DIM}{detail}{_RESET}")
        print()

    print(f"  {_DIM}{'─' * 64}{_RESET}")
    print(f"  {_DIM}Priority scheme: TradePriorityScheme | Conflict: HighestPriorityWins{_RESET}")
    print()

    await network.hub.close()


if __name__ == "__main__":
    asyncio.run(main())
