# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ContribTests

on:
  pull_request:
    branches: ["main"]
    paths:
      - "autogen/**"
      - "test/agentchat/contrib/**"
      - "test/test_browser_utils.py"
      - "test/test_retrieve_utils.py"
      - ".github/workflows/contrib-tests.yml"
      - "pyproject.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
permissions:
  {}
  # actions: read
  # checks: read
  # contents: read
  # deployments: read
jobs:
  WebsiteTest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages and dependencies for all tests
        run: |
          uv pip install --system pytest-cov>=5
      # Force reinstall specific versions to fix typing-extensions import error
      # See: https://community.openai.com/t/error-while-importing-openai-from-open-import-openai/578166/29
      - name: Force install specific versions of typing-extensions and openai
        run: |
          uv pip install --system --force-reinstall "typing-extensions==4.5.0"
          uv pip install --system --force-reinstall "openai==1.8.0"
      - name: Install packages and dependencies for Documentation
        run: |
          uv pip install --system -e "."
          uv pip install --system pydoc-markdown pyyaml termcolor nbclient
          # Pin databind packages as version 4.5.0 is not compatible with pydoc-markdown.
          uv pip install --system databind.core==4.4.2 databind.json==4.4.2
      - name: Coverage
        run: |
          pytest test/website/test_process_api_reference.py test/website/test_process_notebooks.py --skip-openai
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
