name: docs

on:
  pull_request:
    branches: [main]
    path:
      - "autogen/**"
      - "website/**"
      - ".github/workflows/deploy-website.yml"
  push:
    branches: [main]
    path:
      - "autogen/**"
      - "website/**"
      - ".github/workflows/deploy-website.yml"
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
permissions:
  contents: write
jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydoc-markdown pyyaml termcolor nbconvert
          # Pin databind packages as version 4.5.0 is not compatible with pydoc-markdown.
          pip install databind.core==4.4.2 databind.json==4.4.2

      - name: Install quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Generate API documentation
        run: |
          python ./process_api_reference.py
        working-directory: website

      - name: Convert Jupyter notebooks to MDX
        run: |
          python ./process_notebooks.py render
        working-directory: website

      - name: Prepare website content
        run: |
          # Create a temporary directory for filtered content
          mkdir -p temp_website

          # Copy files except .ipynb, node_modules, .quarto, and .gitignore
          find . -type f -not -path "*/node_modules/*" -not -path "*/.quarto/*" -not -name "*.ipynb" -not -name ".gitignore" -exec cp --parents {} temp_website/ \;

  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydoc-markdown pyyaml termcolor nbconvert
          # Pin databind packages as version 4.5.0 is not compatible with pydoc-markdown.
          pip install databind.core==4.4.2 databind.json==4.4.2

      - name: Install quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Generate API documentation
        run: |
          python ./process_api_reference.py
        working-directory: website

      - name: Convert Jupyter notebooks to MDX
        run: |
          python ./process_notebooks.py render
        working-directory: website

      - name: Prepare website content
        run: |
          # Create a temporary directory for filtered content
          mkdir -p temp_website

          # Copy files except .ipynb, node_modules, .quarto, and .gitignore
          find . -type f -not -path "*/node_modules/*" -not -path "*/.quarto/*" -not -name "*.ipynb" -not -name ".gitignore" -exec cp --parents {} temp_website/ \;

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: temp_website/website
