name: Check docs for broken links

on:
  workflow_run:
    workflows: ["mintlify docs"]
    types:
      - completed

jobs:
  check-broken-link:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        # with:
        #   go-version: '^1.13.1' # The Go version to download (if necessary) and use.
        run: go install github.com/raviqqe/muffet/v2@latest

      # - name: Sleep for 5 minutes
      #   run: sleep 300

      - name: Check links using container
        run: ./scripts/broken-links-check.sh
