name: Check docs for broken links

on:
  workflow_run:
    types:
      - completed
    workflows: ["mintlify docs"]

jobs:
  check-broken-link:
    name: Check docs for broken links
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Sleep for 5 minutes
        run: sleep 300
      - name: Check links using container
        run: ./scripts/broken-links-check.sh
