name: Check docs for broken links

on:
  workflow_call:
    inputs:
      event_name:
        required: true
        type: string

jobs:
  check-broken-link:
    if: inputs.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 5 minutes
        run: sleep 300

      - name: Check links using container
        run: ./scripts/broken-links-check.sh
