name: Check docs for broken links

on:
  workflow_run:
    workflows: ["mintlify docs"]
    types:
      - completed

jobs:
  check-broken-link:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Sleep for 5 minutes
        run: sleep 300

      - name: Check links using container
        run: ./scripts/broken-links-check.sh
