name: Check docs for broken links

on:
  workflow_run:
    workflows: ["mintlify docs"]
    types:
      - completed
    branches: [main]

jobs:
  check-broken-link:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event != 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Sleep for 5 minutes
        run: sleep 300

      - name: Check links using container
        run: ./scripts/broken-links-check.sh
